// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCkGEoPIBHt60VSGrKSpL9752Ulnx9NuI',
    appId: '1:941929135113:web:a83acbfca0547236c6ccd8',
    messagingSenderId: '941929135113',
    projectId: 'facebook-clone-flutter',
    authDomain: 'facebook-clone-flutter.firebaseapp.com',
    storageBucket: 'facebook-clone-flutter.appspot.com',
    measurementId: 'G-JFJPW4FYCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsb0QiD8a-KPadwHk5neenMiA4xkcvyc',
    appId: '1:941929135113:android:b6e68bb2b3548673c6ccd8',
    messagingSenderId: '941929135113',
    projectId: 'facebook-clone-flutter',
    storageBucket: 'facebook-clone-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuUFTwy4ldcd-hhlNljwA8J7jTvev0sk',
    appId: '1:941929135113:ios:2c4136233afe5c19c6ccd8',
    messagingSenderId: '941929135113',
    projectId: 'facebook-clone-flutter',
    storageBucket: 'facebook-clone-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtuUFTwy4ldcd-hhlNljwA8J7jTvev0sk',
    appId: '1:941929135113:ios:3b75c2471bc17a0fc6ccd8',
    messagingSenderId: '941929135113',
    projectId: 'facebook-clone-flutter',
    storageBucket: 'facebook-clone-flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
